#pragma once

/* #undef PAL_UNIX_NAME */
#define HAVE_STAT64 0
#define HAVE_PIPE2 0
#define HAVE_STAT_BIRTHTIME 0
#define HAVE_GNU_STRERROR_R 0
#define HAVE_DIRENT_NAME_LEN 0
#define HAVE_MNTINFO 0
#define HAVE_STATFS_FSTYPENAME 0
#define HAVE_STATVFS_FSTYPENAME 0
#define HAVE_STRCPY_S 1
#define HAVE_STRLCPY 0
#define HAVE_SHM_OPEN_THAT_WORKS_WELL_ENOUGH_WITH_MMAP 0
#define HAVE_POSIX_ADVISE 0
#define PRIORITY_REQUIRES_INT_WHO 0
#define KEVENT_REQUIRES_INT_PARAMS 0
#define HAVE_IN6_U 0
#define HAVE_U6_ADDR 0
#define HAVE_IOCTL 0
#define HAVE_TIOCGWINSZ 0
#define HAVE_SCHED_GETAFFINITY 0
#define HAVE_SCHED_SETAFFINITY 0
#define KEVENT_HAS_VOID_UDATA 0
#define HAVE_FDS_BITS 0
#define HAVE_PRIVATE_FDS_BITS 0
#define HAVE_STATFS 0
#define HAVE_EPOLL 0
#define HAVE_KQUEUE 0
#define HAVE_SENDFILE 0
#define HAVE_FCOPYFILE 0
#define HAVE_GETHOSTBYNAME_R 0
#define HAVE_GETHOSTBYADDR_R 0
#define HAVE_GETPEEREID 0
#define HAVE_SUPPORT_FOR_DUAL_MODE_IPV4_PACKET_INFO 0
#define HAVE_THREAD_SAFE_GETHOSTBYNAME_AND_GETHOSTBYADDR 0
#define HAVE_TCGETATTR 0
#define HAVE_TCSETATTR 0
#define HAVE_ECHO 0
#define HAVE_ICANON 0
#define HAVE_TCSANOW 0
#define HAVE_IN_PKTINFO 0
#define HAVE_IP_MREQN 0
#define HAVE_TCP_VAR_H 0
#define HAVE_RT_MSGHDR 0
#define HAVE_SYS_SYSCTL_H 0
#define HAVE_LINUX_RTNETLINK_H 0
#define HAVE_GETDOMAINNAME_SIZET 0
#define HAVE_INOTIFY 0
#define HAVE_CLOCK_MONOTONIC 0
#define HAVE_MACH_ABSOLUTE_TIME 0
#define HAVE_CURLM_ADDED_ALREADY 0
#define HAVE_CURL_HTTP_VERSION_2_0 0
#define HAVE_CURLPIPE_MULTIPLEX 0
#define HAVE_CURL_SSLVERSION_TLSv1_012 0
#define HAVE_TCP_H_TCPSTATE_ENUM 0
#define HAVE_TCP_FSM_H 0
#define HAVE_GSSFW_HEADERS 0
#define HAVE_GSS_SPNEGO_MECHANISM 0
#define HAVE_GSS_KRB5_CRED_NO_CI_FLAGS_X 0
#define HAVE_HEIMDAL_HEADERS 0

// Mac OS X has stat64, but it is deprecated since plain stat now
// provides the same 64-bit aware struct when targeting OS X > 10.5
// and not passing _DARWIN_NO_64_BIT_INODE.
#ifdef __APPLE__
#undef HAVE_STAT64
#define HAVE_STAT64 0
#endif
